"""Controlled Sensor Fault Injection Layer for SKYGUARD.

Implements physically and plausibly interpretable sensor anomalies:
- SPIKE: Sudden abnormal transient observation.
- FROZEN: Stuck sensor holding identical values across observations.
- COMMUNICATION: Channel-level null fields or transmission packet drops.
- DRIFT: Gradual accumulation of sensor bias over time.

Adheres strictly to the frozen M1-A contract in backend/schemas.py.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Literal, Optional, Union
from backend.schemas import Measurements


def normalize_param_name(name: str) -> str:
    """Normalize user-supplied parameter names to Measurements field names."""
    mapping = {
        "temperature": "temperature_c",
        "temperature_c": "temperature_c",
        "temp": "temperature_c",
        "humidity": "relative_humidity_pct",
        "relative_humidity": "relative_humidity_pct",
        "relative_humidity_pct": "relative_humidity_pct",
        "pressure": "pressure_hpa",
        "pressure_hpa": "pressure_hpa",
    }
    return mapping.get(name.lower(), name)


class BaseFault(ABC):
    """Abstract base class for controlled sensor fault transformations."""

    @abstractmethod
    def transform(self, step: int, measurements: Measurements) -> Optional[Measurements]:
        """Apply fault transformation to measurements.
        
        Args:
            step: Current 1-indexed simulation timestep.
            measurements: Pristine measurements generated by the virtual station.
            
        Returns:
            Transformed Measurements object, or None if the observation is dropped
            (e.g., in a packet drop communication failure).
        """
        pass

    def reset(self) -> None:
        """Reset any internal latch/accumulation state."""
        pass


class SpikeFault(BaseFault):
    """Introduces a sudden abnormal transient observation."""

    def __init__(
        self,
        parameter: str = "temperature_c",
        magnitude: float = 18.0,
        start_step: int = 5,
        duration: int = 1,
    ) -> None:
        self.parameter = normalize_param_name(parameter)
        self.magnitude = magnitude
        self.start_step = start_step
        self.duration = duration

    def transform(self, step: int, measurements: Measurements) -> Optional[Measurements]:
        if self.start_step <= step < self.start_step + self.duration:
            data = measurements.model_dump()
            current_val = data.get(self.parameter)
            if current_val is not None:
                new_val = round(current_val + self.magnitude, 2)
                # Keep humidity bounded if humidity is spiked
                if self.parameter == "relative_humidity_pct":
                    new_val = max(0.0, min(100.0, new_val))
                data[self.parameter] = new_val
                return Measurements.model_validate(data)
        return measurements


class FrozenFault(BaseFault):
    """Holds one or more sensor values constant across multiple observations."""

    def __init__(
        self,
        parameters: Optional[Union[str, List[str]]] = None,
        start_step: int = 4,
        duration: Optional[int] = None,
    ) -> None:
        if parameters is None:
            self.parameters = ["temperature_c"]
        elif isinstance(parameters, str):
            self.parameters = [normalize_param_name(parameters)]
        else:
            self.parameters = [normalize_param_name(p) for p in parameters]

        self.start_step = start_step
        self.duration = duration
        self._latched_values: Dict[str, Optional[float]] = {}
        self._is_latched = False

    def reset(self) -> None:
        self._latched_values.clear()
        self._is_latched = False

    def transform(self, step: int, measurements: Measurements) -> Optional[Measurements]:
        is_active = step >= self.start_step
        if self.duration is not None:
            is_active = is_active and (step < self.start_step + self.duration)

        if is_active:
            data = measurements.model_dump()
            if not self._is_latched:
                for param in self.parameters:
                    self._latched_values[param] = data.get(param)
                self._is_latched = True

            for param in self.parameters:
                data[param] = self._latched_values.get(param)

            return Measurements.model_validate(data)

        return measurements


class DriftFault(BaseFault):
    """Introduces a gradual cumulative sensor bias over time."""

    def __init__(
        self,
        parameter: str = "temperature_c",
        rate: float = 0.3,
        start_step: int = 3,
        duration: Optional[int] = None,
    ) -> None:
        self.parameter = normalize_param_name(parameter)
        self.rate = rate
        self.start_step = start_step
        self.duration = duration

    def transform(self, step: int, measurements: Measurements) -> Optional[Measurements]:
        is_active = step >= self.start_step
        if self.duration is not None:
            is_active = is_active and (step < self.start_step + self.duration)

        if is_active:
            elapsed_steps = step - self.start_step + 1
            bias = self.rate * elapsed_steps
            data = measurements.model_dump()
            current_val = data.get(self.parameter)
            if current_val is not None:
                new_val = round(current_val + bias, 2)
                if self.parameter == "relative_humidity_pct":
                    new_val = max(0.0, min(100.0, new_val))
                data[self.parameter] = new_val
                return Measurements.model_validate(data)

        return measurements


class CommunicationFault(BaseFault):
    """Models telemetry or sensor communication failures according to the M1-A contract.
    
    Modes:
    - 'channel_null': Individual sensor channel fails to report (field is None/null).
      Never replaces missing data with 0 or placeholder numbers.
    - 'packet_drop': Transmission packet is dropped entirely; the observation
      is omitted from the network broadcast for this timestep.
    """

    def __init__(
        self,
        mode: Literal["channel_null", "packet_drop"] = "channel_null",
        parameters: Optional[Union[str, List[str]]] = None,
        start_step: int = 4,
        duration: Optional[int] = None,
    ) -> None:
        self.mode = mode
        if parameters is None:
            self.parameters = ["temperature_c"]
        elif isinstance(parameters, str):
            self.parameters = [normalize_param_name(parameters)]
        else:
            self.parameters = [normalize_param_name(p) for p in parameters]

        self.start_step = start_step
        self.duration = duration

    def transform(self, step: int, measurements: Measurements) -> Optional[Measurements]:
        is_active = step >= self.start_step
        if self.duration is not None:
            is_active = is_active and (step < self.start_step + self.duration)

        if not is_active:
            return measurements

        if self.mode == "packet_drop":
            return None

        # channel_null mode: set target channels to None
        data = measurements.model_dump()
        for param in self.parameters:
            data[param] = None

        return Measurements.model_validate(data)


def create_fault(fault_type: str, **kwargs: Any) -> BaseFault:
    """Factory helper to instantiate a fault by type string."""
    ft = fault_type.upper()
    if ft == "SPIKE":
        return SpikeFault(**kwargs)
    elif ft == "FROZEN":
        return FrozenFault(**kwargs)
    elif ft == "DRIFT":
        return DriftFault(**kwargs)
    elif ft in ("COMMUNICATION", "COMM"):
        return CommunicationFault(**kwargs)
    else:
        raise ValueError(f"Unknown fault type: {fault_type}. Expected SPIKE, FROZEN, DRIFT, or COMMUNICATION.")
