"""
SKYGUARD FastAPI Backend Application Entry Point

Exposes REST API endpoints for station management, observation ingestion,
decision retrieval, evidence inspection, scenario execution, and network status.
"""

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from typing import List, Dict, Any

from backend.models import (
    IngestionPayload, RawObservation, DecisionObject, StationInfo,
    StationHistoryResponse, NetworkStatus, ScenarioRequest
)
from backend.store import store
from simulator.generator import execute_scenario

app = FastAPI(
    title="SKYGUARD Decision Engine API",
    description="Backend API for Automatic Weather Station (AWS) Data Trust & Sensor Health Decision Support",
    version="1.0.0"
)

# Enable CORS for dashboard integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/healthz")
def health_check():
    return {"status": "healthy", "service": "skyguard-backend"}


# --- STATIONS API ---

@app.get("/stations", response_model=Dict[str, List[StationInfo]])
@app.get("/api/v1/stations", response_model=Dict[str, List[StationInfo]])
def get_stations():
    """Returns available AWS stations."""
    stations = store.get_all_stations()
    return {"stations": stations}


@app.get("/stations/{station_id}", response_model=StationInfo)
@app.get("/api/v1/stations/{station_id}", response_model=StationInfo)
def get_station(station_id: str):
    """Returns station information and current relevant telemetry."""
    station = store.get_station(station_id)
    if not station:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Station '{station_id}' not found."
        )
    return station


@app.get("/stations/{station_id}/history", response_model=StationHistoryResponse)
@app.get("/api/v1/stations/{station_id}/history", response_model=StationHistoryResponse)
def get_station_history(station_id: str):
    """Returns historical observations for the station."""
    station = store.get_station(station_id)
    if not station:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Station '{station_id}' not found."
        )
    history = store.get_history(station_id)
    return StationHistoryResponse(
        station_id=station_id,
        history=history,
        total_records=len(history)
    )


# --- INGESTION API ---

@app.post("/ingest", response_model=DecisionObject)
@app.post("/api/v1/ingest", response_model=DecisionObject)
def ingest_observation(payload: IngestionPayload):
    """
    Ingests canonical observation payloads.
    Missing values remain null and are NEVER converted to zero.
    Passes observation through the decision pipeline.
    """
    try:
        decision = store.ingest_observation(payload)
        return decision
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Observation ingestion failed: {str(e)}"
        )


# --- DECISION API ---

@app.get("/decision/{station_id}", response_model=DecisionObject)
@app.get("/api/v1/decision/{station_id}", response_model=DecisionObject)
def get_decision(station_id: str):
    """
    Returns the decision produced by the actual SKYGUARD decision engine.
    State is NEVER calculated in the API layer or frontend.
    """
    decision = store.get_decision(station_id)
    if not decision:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Decision unavailable for station '{station_id}'."
        )
    return decision


# --- EVIDENCE API ---

@app.get("/evidence/{station_id}")
@app.get("/api/v1/evidence/{station_id}")
def get_evidence(station_id: str):
    """
    Exposes evidence generated by the real SKYGUARD pipeline,
    separating World Evidence and Sensor Evidence.
    """
    decision = store.get_decision(station_id)
    if not decision:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Evidence unavailable for station '{station_id}'."
        )
    return {
        "station_id": station_id,
        "timestamp": decision.timestamp,
        "world_evidence": decision.world_evidence,
        "sensor_evidence": decision.sensor_evidence,
        "evidence_quality": decision.evidence_quality,
        "provenance": decision.provenance,
        "independence": decision.independence
    }


# --- SCENARIO API ---

@app.post("/scenario", response_model=DecisionObject)
@app.post("/api/v1/scenario", response_model=DecisionObject)
def run_scenario(req: ScenarioRequest):
    """
    Triggers scenario generator which produces observations that pass through
    the normal ingestion pipeline and decision engine.
    """
    try:
        target_id = req.station_id or "AWS-03"
        resulting_decision = execute_scenario(
            scenario=req.scenario,
            station_id=target_id,
            mode=req.mode
        )
        return resulting_decision
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Scenario execution failed: {str(e)}"
        )


# --- NETWORK STATUS API ---

@app.get("/network/status", response_model=NetworkStatus)
@app.get("/api/v1/network/status", response_model=NetworkStatus)
def get_network_status():
    """Returns network-level status summary."""
    return store.get_network_status()
